name: E2E Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    e2e-tests:
        name: E2E tests on Node ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['20']
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build Assets
              run: npm run build

            - name: Start WordPress Environment
              run: npm run wp-env -- start

            - name: Run E2E tests
              run: npm run test:e2e

            - name: Stop WordPress Environment
              if: always()
              run: npm run wp-env -- stop
